site_name: EdgeAI-Lab

# Repository
# repo_name: Notebook
# repo_url: https://github.com/edgeML/notebook

nav:
    # - Home: about.md
    # - About Me: about.md
    - Android:
      - Android开机自启:
        - Launcher: Android/android_source_code/android_launcher.md
        - 开机广播: Android/android_source_code/android_broadcast_boot.md
      - Android6.0源码修改:
        - 去掉USB权限申请对话框: Android/android_source_code/android_remove_usb_permission_dialog.md
        - 修改屏幕默认亮度: Android/android_source_code/android_screen_brightness.md
        - 彻底隐藏虚拟导航键: Android/android_source_code/android_hide_virtual_navigation_key.md
        - 默认开启USB调试功能: Android/android_source_code/android_enable_usb_debug.md
      
      - Android应用开发:
        - RecycleView: Android/Application/RecycleView.md
        - Android 屏幕适配: Android/android_screen_adapter/android_screen_adapter.md

      - Android NDK开发:
        - NDK开发: Android/android_ndk/android_ndk.md
        - GCC&Clang&LLVM的关系: Embedded System/gcc_clang_llvm.md
        - 交叉编译示例OPUS: Android/android_ndk/cross-compile_opus_for_android.md
        - 交叉编译ijkplayer: Android/android_ndk/ijkpalyer_for_rtsp_compile.md
        - ART: Android/android_ndk/android_art.md
        - Android CMake知识点: Android/android_ndk/android_cmake.md
        - Android交叉编译OpenCV: Android/android_ndk/cross-compile_opencv_for_android.md
        
      - Android编译系统: Android/android_compiler_system/android_compile_system.md
      
      - Java:
        - Ubuntu中配置Java: Android/java/ubuntu_config_java.md
        - Swing: Android/java/java_ui_swing.md

    - C/C++: 
        - 你需要知道的N个C语言问题:
          - C内存模型: Embedded System/c&c++/c_memory_layout.md
          - C宏定义#与##: Embedded System/c&c++/c_micro_jing.md
          - C指针: Embedded System/c&c++/c_pointer.md
          - pragma pack(): Embedded System/c&c++/c_pragma.md
          - typedef使用注意: Embedded System/c&c++/typedef_tips.md

        - 补码: Embedded System/c&c++/complement.md
        - pkg-config: Embedded System/c&c++/pkg_config.md
        - ASCII Table: Embedded System/c&c++/ascii_table.md
        - C操作符优先级: Embedded System\c&c++\c_operator_precedence.md
        - CMake用法: Embedded System\c&c++\cmake_usage.md
        - C代码片段: Embedded System\c&c++\snippet.md


    - STM32: 
        - STM32经典书籍: Embedded System\STM32\stm32_books.md
        - STM32的三种启动方式: Embedded System\STM32\stm32_boot_configure.md
        - STM32在SRAM中运行代码: Embedded System\STM32\stm32_run_code_in_ram.md
        - STM32的启动流程: Embedded System\STM32\stm32_boot.md
        - STM32 initcall机制-Keil: Embedded System\STM32\stm32_initcall_keil.md
        - STM32 initcall机制-GCC: Embedded System\STM32\stm32_initcall_gcc.md
        - 调试器背后的秘密: Embedded System\STM32\debuger_flash_programming.md
        - ARM链接脚本: Embedded System\STM32\stm32_link_script.md
        - Keil AXF文件和BIN文件分析: Embedded System\STM32\stm32_elf_bin_file_analysis.md
        - ARM汇编: Embedded System\STM32\arm_assembly.md

        - STM32外设:
          - STM32串口编程之中断方式: Embedded System/STM32/stm32_hal_uart.md
          - STM32定时器编程之定时中断: Embedded System/STM32/stm32_hal_uart.md
          - STM32定时器编程之PWM: Embedded System/STM32/stm32_hal_uart.md
          - STM32 SPI: Embedded System/STM32/stm32_spi.md
          - Flash 磨损均衡算法: Embedded System/STM32/stm32_flash_erase_leveling.md
          - STM32软件复位: Embedded System\STM32\stm32_sw_reset.md

        - Motor Control: 
          - 转矩: Embedded System\motor_control\torque.md
          - 直流刷式电机: Embedded System\motor_control\dc_motor_driver_chip.md
          - 步进电机: Embedded System\motor_control\stepper_motor_driver_chip.md
          - STM32控制42步进电机: Embedded System/STM32/stm32_io_drive_42stepper_l298n.md

        - STM32开发神兵利器:
          - JScope RTT模式: Embedded System\STM32\tools\jscope_rtt.md
          - JScope HSS模式: Embedded System\STM32\tools\jscope_hss.md
          - JLink RTT: Embedded System\STM32\tools\rtt.md

    - Linux:
        - 开发环境相关: 
          - VirtualBox开发环境搭建: Embedded System\linux\embedded_linux_dev_env\virtual_box_env.md
          - Ubuntu中构建内核源码树: Embedded System\linux\embedded_linux_dev_env\build_linux_source_tree_on_ubuntu.md
          - samba服务配置: Embedded System\linux\embedded_linux_dev_env\samba_server.md
          - FTP服务配置: Embedded System\linux\embedded_linux_dev_env\ftp_server.md
          - TFTP服务配置: Embedded System\linux\embedded_linux_dev_env\tftp_server.md
          - NFS: Embedded System\linux\embedded_linux_dev_env\nfs_server.md
          - ARM交叉编译工具: Embedded System\linux\embedded_linux_dev_env\arm_compiler.md
          - Ubuntu启动错误: Embedded System\linux\embedded_linux_dev_env\ubuntu_boot_error.md
        
        - JZ2440开发:
          - OpenJTAG: Embedded System\linux\jz2440\easy_open_jtag.md
          - Uboot移植: Embedded System\linux\jz2440\uboot_porting.md
          - Linux Kernel移植: Embedded System\linux\jz2440\linux_kernel_porting.md
          - CMake交叉编译: Embedded System\linux\jz2440\cmake_cross_compile.md
          - JZ2440 dev tips: Embedded System\linux\jz2440\jz2440_dev_tips.md

        - 安全的使用rm: Embedded System\linux\embedded_linux_dev_env\rm.md

        - GNU make:
          - GNU make中的2种变量: Embedded System\linux\makefile\two_flavors_of_variables.md

        - GCC编译动态链接库: Embedded System/gcc_dynamic_linking_library.md
        - 常用shell命令: Embedded System/linux_shell_cmd.md
        - Linux Shell脚本编程: Embedded System/linux_shell_program.md
        - GCC&Clang&LLVM的关系: Embedded System/gcc_clang_llvm.md
        
        - RK3399:
          - 命令行连接WiFi热点: Embedded System\rk3399_cli_connect_wifi.md

    - Other:
      - Computer Science:
        - 字符集: Embedded System\cs\character_set.md

      - Machine Learning:
        - 机器学习基础: ML/ml_basics.md
        - Tensorflow安装: ML\tensorflow_install.md
        - Tensorflow模型转换: ML\tensorflow_model.md
        - 嵌入式机器学习: 
          - 00：STM32图像分类: ML\how_to_run_dl_model_on_stm32.md

      - Python:
        - matplotlib使用: Python/matplotlib.md
        - 三角函数: Python/python_trigonometric.md
        - 录音与播放: Python/python_record_play.md  
        - Python代码片段: Python\snippet.md
        - Python字符串格式化: Python/python_string_format.md

      - Computer Vision:
        - caffe: Computer Vision/caffe.md
        - cv_library: Computer Vision/cv_library.md
        - OpenCV4Android: Computer Vision/OpenCV4Android_001.md

      - Multimedia:
        - VOD: Multimedia/AliyunVOD/get_play_url.md
        - 光学知识点: Multimedia/optical.md
        - AAC编码: Multimedia/aac.md
        - 彻底理解YUV格式: Multimedia/yuv.md
        - 音视频同步: Multimedia/av_synchronization.md
        - nginx: Multimedia/nginx.md
        - Linux Shell命令: Multimedia/linux_shell_cmd_for_multimedia.md
        - FFMPEG编译: Multimedia/ffmpeg_compile.md
        - FFMPEG命令: Multimedia/ffmpeg_command.md
        - FFMPEG API: Multimedia/ffmpeg_api.md
        - EasyDarwin: Multimedia/easydarwin.md
        - PCM: Multimedia/pcm.md
        - WAV: Multimedia/wav_foramt.md
        - OPUS: Multimedia/opus.md
        - Ogg: Multimedia/Ogg.md

      - Hardware:
        - 电池工作时间的计算: Hardware/battery_work_time.md

      - ESP8266: Embedded System/ESP8266.md

    - Tools:
      - MkDocs搭建个人WiKi知识管理系统: 
        - 1.MkDocs - 初识: Tools\mkdocs\mkdocs_intro.md
        - 2.MkDocs - 部署到Github Pages: Tools\mkdocs\mkdocs_deploy_githubpages.md
        - 3.MkDocs - 部署到Nginx: Tools\mkdocs\mkdocs_deploy_nginx.md
        - 4.MkDocs - Wiki样式配置: Tools\mkdocs\mkdocs_theme.md
      - 嵌入式开发神兵利器: Tools\embedded_develop_tools.md
      - VPN:
        - Shadowsocks Ubuntu客户端: Tools\VPN\Shadowsocks_client_for_ubuntu.md
        - ShadowsocksR Ubuntu客户端: Tools\VPN\ShadowsocksR_client_for_ubuntu.md
        - ShadowsocksR Ubuntu服务端: Tools\VPN\ShadowsocksR_server_for_ubuntu.md

      - VIM:
        - VIM插件配置: Tools\VIM\vim_configure.md
        - VIM使用: Tools\VIM\vim_usage.md 

      - Markdown中的一些技巧: Tools\markdown.md
      - git command: Tools/git_command.md

      - 局域网访问Jupyter Notebook: Tools/JupyterNotebook.md
      - UML: Tools/PlantUML.md

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Frank'
    
# Configuration
theme:
  # name: 'mkdocs'
  # name: 'flatly'
  name: 'united'
  # name: 'simplex'

  # default is en
  language: 'en'

  # default is true
  highlightjs: true

  # deafult is github
  hljs_style: github
  hljs_languages:
    - c
    - c++
    - nginx
    - java
    - python
    - shell session
    - yaml
    
extra:
# Chinese is not supported  
  search:
    language: 'en'
      
# Extensions
markdown_extensions:
  - admonition
  - footnotes

  # code style
  # - codehilite:
  #     guess_lang: false
  #     linenums: false
  - toc:
      permalink: '#'

extra_css:
    - css/extra.css

plugins:
    - search