site_name: Notebook

# Repository
repo_name: Notebook
repo_url: https://github.com/FanHongchuang/notebook

# 404 page
static_templates:
    - 404.html

nav:
    - Home: index.md
    - About Me: about.md
    - Android:
      - Android开机自启:
        - Launcher: Android/android_launcher.md
        - 开机广播: Android/android_broadcast_boot.md
      - Android6.0源码修改:
        - 去掉USB权限申请对话框: Android/android_remove_usb_permission_dialog.md
        - 修改屏幕默认亮度: Android/android_screen_brightness.md
        - 彻底隐藏虚拟导航键: Android/android_hide_virtual_navigation_key.md
        - 默认开启USB调试功能: Android/android_enable_usb_debug.md
      - Android 屏幕适配: Android/android_screen_adapter.md
        
    - ARM-Linux:
      - C/C++: ARM-Linux/c_memory_layout.md
      - Linux:
        - 构建内核源码树: ARM-Linux/build_linux_source_tree.md
        - 常用shell命令: ARM-Linux/linux_shell_cmd.md
        - samba服务配置: ARM-Linux/samba.md
        - Linux Shell脚本编程: ARM-Linux/linux_shell_program.md
      - Zigbee: ARM-Linux/zigbee_keys.md
      
      
    - Computer Vision:
      - Computer Vision: Computer Vision/Computer Vision.md
      
    - Multimedia:
      - Multimedia: Multimedia/Multimedia.md
      
    - Design Pattern:
      - Design Pattern: Design Patterns/Design Patterns.md
      
    - Hardware:
      - Hardware: Hardware/hardware.md
      
    - Tools:
      - UML: Tools/PlantUML.md
      - git command: Tools/git_command.md
      - Python三角函数: Tools/python_trigonometric.md
      - Shadowsock: Tools/Shadowsock.md
   
   

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Hongchaung Fan'
    
# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
    
extra:
  social:
    - type: 'github'
      link: 'https://github.com/FanHongchuang'
      
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
