site_name: Notebook

# Repository
repo_name: Notebook
repo_url: https://github.com/FanHongchuang/notebook

# 404 page
static_templates:
    - 404.html

nav:
    - Home: index.md
    - About Me: about.md
    - Android:
      - Android开机自启:
        - Launcher: Android/android_launcher.md
        - 开机广播: Android/android_broadcast_boot.md
      - Android6.0源码修改:
        - 去掉USB权限申请对话框: Android/android_remove_usb_permission_dialog.md
        - 修改屏幕默认亮度: Android/android_screen_brightness.md
        - 彻底隐藏虚拟导航键: Android/android_hide_virtual_navigation_key.md
        - 默认开启USB调试功能: Android/android_enable_usb_debug.md
      - Android 屏幕适配: Android/android_screen_adapter.md
      - Android NDK开发:
        - NDK知识点: Android/android_ndk.md
        - GCC&Clang&LLVM的关系: Embedded System/gcc_clang_llvm.md
        - 交叉编译示例OPUS: Android/cross-compile_opus_for_android.md
        - 交叉编译ijkplayer: Android/ijkpalyer_for_rtsp_compile.md
        - JNI知识点: Android/jni.md
        - ART: Android/android_art.md
        - Android CMake知识点: Android/android_cmake.md
        - Android交叉编译OpenCV: Android/cross-compile_opencv_for_android.md
        - Ubuntu中配置Java: Android/ubuntu_config_java.md
      
      - Java:
        - Swing: Android/java_ui_swing.md

    - Embedded System:
      - C/C++: 
        - C内存模型: Embedded System/c_memory_layout.md
        - CRC16: Embedded System/crc16.md
        - C宏定义#与##: Embedded System/c_micro_jing.md
        - 补码: Embedded System/complement.md
        - C指针: Embedded System/c_pointer.md
        - pragma pack(): Embedded System/c_pragma.md
        - pkg-config: Embedded System/pkg_config.md
        - typedef使用注意: Embedded System/typedef_tips.md

      - ESP8266: Embedded System/ESP8266.md

      - STM32: 
        - STM32串口编程之中断方式: Embedded System/STM32/stm32_hal_uart.md
        - STM32定时器编程之定时中断: Embedded System/STM32/stm32_hal_uart.md
        - STM32定时器编程之PWM: Embedded System/STM32/stm32_hal_uart.md
        - STM32 SPI: Embedded System/STM32/stm32_spi.md
        - STM32控制42步进电机: Embedded System/STM32/stm32_io_drive_42stepper_l298n.md
        - Flash 磨损均衡算法: Embedded System/STM32/stm32_flash_erase_leveling.md
        - 初始化函数的另一种写法: Embedded System/STM32/stm32_module_init_like.linux.md

      - Linux:
        - GCC编译动态链接库: Embedded System/gcc_dynamic_linking_library.md
        - 构建内核源码树: Embedded System/build_linux_source_tree.md
        - 常用shell命令: Embedded System/linux_shell_cmd.md
        - samba服务配置: Embedded System/samba.md
        - FTP服务配置: Embedded System/ftp_server_build.md
        - Linux Shell脚本编程: Embedded System/linux_shell_program.md
        - GCC&Clang&LLVM的关系: Embedded System/gcc_clang_llvm.md
      - Zigbee: Embedded System/zigbee_keys.md
      - NanoPC RK3399:  Embedded System/nanopc_m4.md
      
      - ASCII Table: Embedded System/ascii_table.md
        
    - Python: 
        - matplotlib使用: Python/matplotlib.md
        - 三角函数: Python/python_trigonometric.md
        - 录音与播放: Python/python_record_play.md  
        - CRC16: Python/crc16.md
        - Python字符串格式化: Python/python_string_format.md
      
    - Computer Vision:
      - caffe: Computer Vision/caffe.md
      - cv_library: Computer Vision/cv_library.md
      - OpenCV4Android: Computer Vision/OpenCV4Android_001.md
      
    - Multimedia:
      - 光学知识点: Multimedia/optical.md
      - 彻底理解YUV格式: Multimedia/yuv.md
      - 音视频同步: Multimedia/av_synchronization.md
      - nginx: Multimedia/compile_install_nginx.md
      - Linux Shell命令: Multimedia/linux_shell_cmd_for_multimedia.md
      - FFMPEG编译: Multimedia/ffmpeg_compile.md
      - FFMPEG命令: Multimedia/ffmpeg_command.md
      - FFMPEG API: Multimedia/ffmpeg_api.md
      - EasyDarwin: Multimedia/easydarwin.md
      - PCM: Multimedia/pcm.md
      - WAV: Multimedia/wav_foramt.md
      - OPUS: Multimedia/opus.md
      - Ogg: Multimedia/Ogg.md

    - Hardware:
      - 电池工作时间的计算: Hardware/battery_work_time.md

    - Tools:
      - UML: Tools/PlantUML.md
      - git command: Tools/git_command.md
      - Shadowsock: Tools/Shadowsock.md
      - Shadowsock命令行配置: Tools/Shadowsock_CML.md
      - 局域网访问Jupyter Notebook: Tools/JupyterNotebook.md
   
   

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Hongchaung Fan'
    
# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
    
extra:
  social:
    - type: 'github'
      link: 'https://github.com/FanHongchuang'
# Chinese is not supported  
  search:
    language: 'en'
      
# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
