site_name: Notebook

# Repository
repo_name: Notebook
repo_url: https://github.com/FanHongchuang/notebook

# 404 page
static_templates:
    - 404.html

nav:
    - Home: index.md
    - About Me: about.md
    - Android:
      - Android开机自启:
        - Launcher: Android/android_launcher.md
        - 开机广播: Android/android_broadcast_boot.md
      - Android6.0源码修改:
        - 去掉USB权限申请对话框: Android/android_remove_usb_permission_dialog.md
        - 修改屏幕默认亮度: Android/android_screen_brightness.md
        - 彻底隐藏虚拟导航键: Android/android_hide_virtual_navigation_key.md
        - 默认开启USB调试功能: Android/android_enable_usb_debug.md
      - Android 屏幕适配: Android/android_screen_adapter.md
      - Android NDK开发:
        - NDK知识点: Android/android_ndk.md
        - GCC&Clang&LLVM的关系: ARM-Linux/gcc_clang_llvm.md
        - 交叉编译示例OPUS: Android/cross-compile_opus_for_android.md
        - 交叉编译ijkplayer: Android/ijkpalyer_for_rtsp_compile.md
        - JNI知识点: Android/jni.md
        - ART: Android/android_art.md
        - Android CMake知识点: Android/android_cmake.md

    - ARM-Linux:
      - C/C++: 
        - C内存模型: ARM-Linux/c_memory_layout.md
        - CRC16: ARM-Linux/crc16.md
        - C宏定义#与##: ARM-Linux/c_micro_jing.md
        - 补码: ARM-Linux/complement.md
        - C指针: ARM-Linux/c_pointer.md
        - pragma pack(): ARM-Linux/c_pragma.md

      - Linux:
        - 构建内核源码树: ARM-Linux/build_linux_source_tree.md
        - 常用shell命令: ARM-Linux/linux_shell_cmd.md
        - samba服务配置: ARM-Linux/samba.md
        - FTP服务配置: ARM-Linux/ftp_server_build.md
        - Linux Shell脚本编程: ARM-Linux/linux_shell_program.md
        - GCC&Clang&LLVM的关系: ARM-Linux/gcc_clang_llvm.md
      - Zigbee: ARM-Linux/zigbee_keys.md
      
      - Java:
        - Swing: ARM-Linux/java_ui_swing.md
      - ASCII Table: ARM-Linux/ascii_table.md
        
    - Python: 
        - 三角函数: Python/python_trigonometric.md
        - 录音与播放: Python/python_record_play.md  
        - CRC16: Python/crc16.md
        - Python字符串格式化: Python/python_string_format.md
      
    - Computer Vision:
      - caffe: Computer Vision/caffe.md
      - cv_library: Computer Vision/cv_library.md
      - OpenCV4Android: Computer Vision/OpenCV4Android_001.md
      
    - Multimedia:
      - 彻底理解YUV格式: Multimedia/yuv.md
      - 音视频同步: Multimedia/av_synchronization.md
      - nginx: Multimedia/compile_install_nginx.md
      - FFMPEG: Multimedia/ffmpeg_command.md
      - EasyDarwin: Multimedia/easydarwin.md
      - PCM: Multimedia/pcm.md
      - WAV: Multimedia/wav_foramt.md
      - OPUS: Multimedia/opus.md
      - Ogg: Multimedia/Ogg.md
      
    - STM32:
      - STM32串口: 
        - STM32串口编程之中断方式: STM32/stm32_hal_uart.md

      - STM32定时器:
        - STM32定时器编程之定时中断: STM32/stm32_hal_uart.md
        - STM32定时器编程之PWM: STM32/stm32_hal_uart.md

      - STM32电机控制:
        - STM32控制42步进电机: STM32/stm32_io_drive_42stepper_l298n.md
      - STM32 Flash操作:
        - Flash 磨损均衡算法: STM32/stm32_flash_erase_leveling.md

    - Hardware:
      - 电池工作时间的计算: Hardware/battery_work_time.md

    - Tools:
      - UML: Tools/PlantUML.md
      - git command: Tools/git_command.md
      - Shadowsock: Tools/Shadowsock.md
      - Shadowsock命令行配置: Tools/Shadowsock_CML.md
      - 局域网访问Jupyter Notebook: Tools/JupyterNotebook.md
   
   

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Hongchaung Fan'
    
# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
    
extra:
  social:
    - type: 'github'
      link: 'https://github.com/FanHongchuang'
# Chinese is not supported  
  search:
    language: 'en'
      
# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
