site_name: Notebook

# Repository
repo_name: Notebook
repo_url: https://github.com/edgeML/notebook

# 404 page
static_templates:
    - 404.html

nav:
    - Home: about.md
    # - About Me: about.md
    - Android:
      - Android开机自启:
        - Launcher: Android/android_source_code/android_launcher.md
        - 开机广播: Android/android_source_code/android_broadcast_boot.md
      - Android6.0源码修改:
        - 去掉USB权限申请对话框: Android/android_source_code/android_remove_usb_permission_dialog.md
        - 修改屏幕默认亮度: Android/android_source_code/android_screen_brightness.md
        - 彻底隐藏虚拟导航键: Android/android_source_code/android_hide_virtual_navigation_key.md
        - 默认开启USB调试功能: Android/android_source_code/android_enable_usb_debug.md
      
      - Android应用开发:
        - RecycleView: Android/Application/RecycleView.md
        - Android 屏幕适配: Android/android_screen_adapter/android_screen_adapter.md

      - Android NDK开发:
        - NDK开发: Android/android_ndk/android_ndk.md
        - GCC&Clang&LLVM的关系: Embedded System/gcc_clang_llvm.md
        - 交叉编译示例OPUS: Android/android_ndk/cross-compile_opus_for_android.md
        - 交叉编译ijkplayer: Android/android_ndk/ijkpalyer_for_rtsp_compile.md
        - ART: Android/android_ndk/android_art.md
        - Android CMake知识点: Android/android_ndk/android_cmake.md
        - Android交叉编译OpenCV: Android/android_ndk/cross-compile_opencv_for_android.md
        
      - Android编译系统: Android/android_compiler_system/android_compile_system.md
      
      - Java:
        - Swing: Android/java/java_ui_swing.md
        - Ubuntu中配置Java: Android/java/ubuntu_config_java.md

    - ML:
      - 机器学习基础: ML/ml_basics.md
      - Tensorflow安装: ML\tensorflow_install.md
      - Tensorflow模型转换: ML\tensorflow_model.md
      - 嵌入式机器学习: 
        - 00~STM32图像分类: ML\how_to_run_dl_model_on_stm32.md

      - Python:
        - matplotlib使用: Python/matplotlib.md
        - 三角函数: Python/python_trigonometric.md
        - 录音与播放: Python/python_record_play.md  
        - CRC16: Python/crc16.md
        - Python字符串格式化: Python/python_string_format.md


    - Embedded:
      - C/C++: 
        - C内存模型: Embedded System/c&c++/c_memory_layout.md
        - CRC16: Embedded System/c&c++/crc16.md
        - C宏定义#与##: Embedded System/c&c++/c_micro_jing.md
        - 补码: Embedded System/c&c++/complement.md
        - C指针: Embedded System/c&c++/c_pointer.md
        - pragma pack(): Embedded System/c&c++/c_pragma.md
        - pkg-config: Embedded System/c&c++/pkg_config.md
        - typedef使用注意: Embedded System/c&c++/typedef_tips.md
        - ASCII Table: Embedded System/c&c++/ascii_table.md
        - CMake用法: Embedded System\c&c++\cmake_usage.md

      - ESP8266: Embedded System/ESP8266.md

      - STM32: 
        - STM32串口编程之中断方式: Embedded System/STM32/stm32_hal_uart.md
        - STM32定时器编程之定时中断: Embedded System/STM32/stm32_hal_uart.md
        - STM32定时器编程之PWM: Embedded System/STM32/stm32_hal_uart.md
        - STM32 SPI: Embedded System/STM32/stm32_spi.md
        - STM32控制42步进电机: Embedded System/STM32/stm32_io_drive_42stepper_l298n.md
        - Flash 磨损均衡算法: Embedded System/STM32/stm32_flash_erase_leveling.md
        - 初始化函数的另一种写法: Embedded System/STM32/stm32_module_init_like.linux.md

      - Linux:
        - 开发环境相关: 
          - VirtualBox开发环境搭建: Embedded System\linux\embedded_linux_dev_env\virtual_box_env.md
          - 构建内核源码树: Embedded System\linux\embedded_linux_dev_env\ubuntu_get_kernel_tree.md
          - samba服务配置: Embedded System\linux\embedded_linux_dev_env\samba.md
          - FTP服务配置: Embedded System\linux\embedded_linux_dev_env\ftp_server_build.md
          - NFS: Embedded System\linux\embedded_linux_dev_env\nfs.md
          - ARM交叉编译工具: Embedded System\linux\embedded_linux_dev_env\arm_compiler.md

        - JZ2440开发:
          - 关于交叉编译工具链: Embedded System\linux\jz2440\cross_compile.md
          
        - GCC编译动态链接库: Embedded System/gcc_dynamic_linking_library.md
        - 常用shell命令: Embedded System/linux_shell_cmd.md
        - Linux Shell脚本编程: Embedded System/linux_shell_program.md
        - GCC&Clang&LLVM的关系: Embedded System/gcc_clang_llvm.md
      - Zigbee: Embedded System/zigbee_keys.md
      - NanoPC RK3399:  Embedded System/nanopc_m4.md

      - Hardware:
        - 电池工作时间的计算: Hardware/battery_work_time.md
      
    - CV:
      - caffe: Computer Vision/caffe.md
      - cv_library: Computer Vision/cv_library.md
      - OpenCV4Android: Computer Vision/OpenCV4Android_001.md

    - Multimedia:
      - VOD: Multimedia/AliyunVOD/get_play_url.md
      - 光学知识点: Multimedia/optical.md
      - AAC编码: Multimedia/aac.md
      - 彻底理解YUV格式: Multimedia/yuv.md
      - 音视频同步: Multimedia/av_synchronization.md
      - nginx: Multimedia/nginx.md
      - Linux Shell命令: Multimedia/linux_shell_cmd_for_multimedia.md
      - FFMPEG编译: Multimedia/ffmpeg_compile.md
      - FFMPEG命令: Multimedia/ffmpeg_command.md
      - FFMPEG API: Multimedia/ffmpeg_api.md
      - EasyDarwin: Multimedia/easydarwin.md
      - PCM: Multimedia/pcm.md
      - WAV: Multimedia/wav_foramt.md
      - OPUS: Multimedia/opus.md
      - Ogg: Multimedia/Ogg.md

    - Tools:
      - 嵌入式开发神兵利器: Tools\embedded_develop_tools.md
      - git command: Tools/git_command.md
      - Shadowsocks: Tools/Shadowsocks.md
      - ShadowsocksR: Tools/ShadowsocksR.md
      - 局域网访问Jupyter Notebook: Tools/JupyterNotebook.md
      - UML: Tools/PlantUML.md
   
   

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Frank'
    
# Configuration
theme:
  # name: 'mkdocs'
  # name: 'flatly'
  name: 'united'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
    
extra:
  social:
    - type: 'github'
      link: 'https://github.com/edgeML'
# Chinese is not supported  
  search:
    language: 'en'

  theme_inverse: true
      
# Extensions
markdown_extensions:
  - admonition
  - footnotes

  # code style
  # - codehilite:
  #     guess_lang: false
  #     linenums: false
  - toc:
      permalink: '#'

plugins:
    - search
    