site_name: EdgeAI-Lab

# Repository
# repo_name: Notebook
# repo_url: https://github.com/edgeML/notebook

nav:
    # - Home: about.md
    # - About Me: about.md
    - Android:
      - Android开机自启:
        - Launcher: Android/android_source_code/android_launcher.md
        - 开机广播: Android/android_source_code/android_broadcast_boot.md
      - Android6.0源码修改:
        - 去掉USB权限申请对话框: Android/android_source_code/android_remove_usb_permission_dialog.md
        - 修改屏幕默认亮度: Android/android_source_code/android_screen_brightness.md
        - 彻底隐藏虚拟导航键: Android/android_source_code/android_hide_virtual_navigation_key.md
        - 默认开启USB调试功能: Android/android_source_code/android_enable_usb_debug.md
        - Android应用获取系统权限: Android/android_source_code/android_get_system_permission.md
        - Android屏蔽权限请求对话框: Android/android_source_code/android_mask_permission_dialog.md
        - Android定制开机Logo: Android/android_source_code/android_power_logo.md
      
      - Android应用开发:
        - RecycleView: Android/Application/RecycleView.md
        - Android 屏幕适配: Android/android_screen_adapter/android_screen_adapter.md

      - Android NDK开发:
        - NDK开发: Android/android_ndk/android_ndk.md
        - GCC&Clang&LLVM的关系: Embedded System/linux/compiler/gcc_clang_llvm.md
        - 交叉编译示例OPUS: Android/android_ndk/cross-compile_opus_for_android.md
        - 交叉编译ijkplayer: Android/android_ndk/ijkpalyer_for_rtsp_compile.md
        - ART: Android/android_ndk/android_art.md
        - Android CMake知识点: Android/android_ndk/android_cmake.md
        - Android交叉编译OpenCV: Android/android_ndk/cross-compile_opencv_for_android.md
        
      - Android编译系统: Android/android_compiler_system/android_compile_system.md
      
      - Java:
        - 串口操作: Android/java/java_serial.md
        - Gradle: 
          - 命令行中使用Gradle创建Java App和Java library: Android/gradle/gradle_getting_start.md
        - Java基础: 
          - 知识点: Android/java/java_base.md
        - JNI: 
          - 一个非常好的JNI入门实例: Android/java/JNI/jni_getting_start.md
          - JNI原理: Android/java/JNI/java_jni_principle.md
        - Ubuntu中配置Java: Android/java/ubuntu_config_java.md
        - 命令行编译Java程序: Android/java/java_compile_command_line.md
        - IntelliJ: 
          - IntelliJ设置Java源码: Android/java/Tools/intelliJ_set_java_code_source.md
          - IntelliJ添加jar文件: Android/java/Tools/intelliJ_add_library.md
        - Swing: Android/java/java_ui_swing.md

    - STM32:
        - Application:
          - 自定义通信协议: Embedded System/STM32/application/protocal.md
          - STM32 initcall机制-Keil: Embedded System/STM32/application/stm32_initcall_keil.md
          - STM32 initcall机制-GCC: Embedded System/STM32/application/stm32_initcall_gcc.md
          - Flash磨损均衡算法: Embedded System/STM32/application/stm32_flash_erase_leveling.md
          - STM32软件复位: Embedded System/STM32/application/stm32_sw_reset.md
      
        - Master:
          - newlib与可重入: Embedded System/STM32/master/newlib_reentrant.md
          - 如何评价MCU的性能: Embedded System/STM32/master/mcu_performance.md
          - STM32的三种启动方式: Embedded System/STM32/master/stm32_boot_configure.md
          - STM32在SRAM中运行代码: Embedded System/STM32/master/stm32_run_code_in_ram.md
          - STM32的启动流程: Embedded System/STM32/master/stm32_boot.md
          - 调试器背后的秘密: Embedded System/STM32/master/debuger_flash_programming.md
          - ARM编译器链接脚本: Embedded System/STM32/master/stm32_link_script.md
          - GNU链接脚本: Embedded System/STM32/master/stm32_gnu_link_script.md
          - Keil AXF文件和BIN文件分析: Embedded System/STM32/master/stm32_elf_bin_file_analysis.md
          - ARM汇编: Embedded System/STM32/master/arm_assembly.md
          - GNU ARM汇编: Embedded System/STM32/master/gnu_assembly.md
          - CortexM3中断: Embedded System/STM32/master/cortexm3_interrupt.md
          - OS特性: Embedded System/STM32/master/os_feature.md
          - 在C中使用ARM汇编（GNU）: Embedded System/STM32/master/use_assembly_in_c.md
        - STM32外设:
          - Systick Timer: Embedded System/STM32/peripheral/systick_timer.md
          - STM32串口编程之中断方式: Embedded System/STM32/peripheral/stm32_hal_uart.md
          - STM32定时器编程之定时中断: Embedded System/STM32/peripheral/stm32_hal_uart.md
          - STM32定时器编程之PWM: Embedded System/STM32/peripheral/stm32_hal_uart.md
          - STM32定时器之产生固定个数的脉冲: Embedded System/STM32/peripheral/stm32_generate_n_number_pluse.md
          - STM32ADC: Embedded System/STM32/peripheral/stm32_adc.md
        - 通信接口:
          - I2C总线: Embedded System/STM32/communication_interface/i2c_bus.md
          - SPI总线: Embedded System/STM32/communication_interface/spi_bus.md
          - 以太网: Embedded System/STM32/communication_interface/ethernet.md
          - CAN总线: 
            - CAN Bus: Embedded System/STM32/communication_interface/CAN/CAN_bus.md
            - STM32 CAN接口: Embedded System/STM32/communication_interface/CAN/STM32_CAN_Application.md
            - CANopen: Embedded System/STM32/communication_interface/CAN/CANopen.md
        - Motor Control: 
          - 转矩: Embedded System/STM32/motor_control/torque.md
          - 无刷电机: Embedded System/STM32/motor_control/brushless_motor.md
          - 直流刷式电机: Embedded System/STM32/motor_control/dc_motor_driver_chip.md
          - 步进电机: Embedded System/STM32/motor_control/stepper_motor_driver_chip.md
          - STM32控制42步进电机: Embedded System/STM32/motor_control/stm32_io_drive_42stepper_l298n.md
        - STM32开发神兵利器:
          - OpenOCD: Embedded System/STM32/tools/openocd.md
          - JScope RTT模式: Embedded System/STM32/tools/jscope_rtt.md
          - JScope HSS模式: Embedded System/STM32/tools/jscope_hss.md
          - JLink RTT: Embedded System/STM32/tools/rtt.md
          - STM32经典书籍: Embedded System/STM32/tools/stm32_books.md

        - STM8:
          - ADC: Embedded System/STM8/adc.md

        - Wireless:
            - Bluetooth:
              - Bluetooth Base: Embedded System/wireless/bluetooth/bluetooth_base.md
              - Bluetooth Stack: Embedded System/wireless/bluetooth/protocal_stack.md
    - RTOS:
        - FreeRTOS:
          - 任务切换: Embedded System/RTOS/freertos/task_switch.md
          - 中断管理: Embedded System/RTOS/freertos/freertos_interrupt_manage.md
          - 任务栈: Embedded System/RTOS/freertos/freertos_task_stack.md
          - 互斥体: Embedded System/RTOS/freertos/mutexes.md
          - 任务通知: Embedded System/RTOS/freertos/freertos_task_notify.md

    - Linux:
        - C/C++: 
          - 你需要知道的N个C语言问题:
            - C内存模型: Embedded System/c&c++/c_memory_layout.md
            - C宏定义#与##: Embedded System/c&c++/c_micro_jing.md
            - C指针: Embedded System/c&c++/c_pointer.md
            - pragma pack(): Embedded System/c&c++/c_pragma.md
            - typedef使用注意: Embedded System/c&c++/typedef_tips.md
            - const与volatile: Embedded System/c&c++/const_volatile.md

          - GDB: Embedded System/c&c++/gdb_usage.md
          - 编译器相关: Embedded System/c&c++/c_compiler.md
          - C与C++相互调用: Embedded System/c&c++/c_c++_call_each_other.md
          - 补码: Embedded System/c&c++/complement.md
          - pkg-config: Embedded System/c&c++/pkg_config.md
          - ASCII Table: Embedded System/c&c++/ascii_table.md
          - C操作符优先级: Embedded System/c&c++/c_operator_precedence.md
          - CMake用法: Embedded System/c&c++/cmake_usage.md
          - C代码片段: Embedded System/c&c++/snippet.md

        - Linux命令:
          - Linux常用命令: Embedded System/linux/linux_cmd/linux_cmd.md
          - 命令行连接WiFi热点: Embedded System/linux/linux_cmd/cli_connect_wifi.md

        - 开发环境相关: 
          - QEMU:
            - QEMU安装: Embedded System/linux/embedded_linux_dev_env/qemu/qemu_install.md
          - WSL与Windows共享文件: Embedded System/linux/embedded_linux_dev_env/wsl_shared_folder.md
          - VirtualBox开发环境搭建: Embedded System/linux/embedded_linux_dev_env/virtual_box_env.md
          - Ubuntu中构建内核源码树: Embedded System/linux/embedded_linux_dev_env/build_linux_source_tree_on_ubuntu.md
          - SSH服务器配置: Embedded System/linux/embedded_linux_dev_env/ssh_server.md
          - samba服务配置: Embedded System/linux/embedded_linux_dev_env/samba_server.md
          - FTP服务配置: Embedded System/linux/embedded_linux_dev_env/ftp_server.md
          - TFTP服务配置: Embedded System/linux/embedded_linux_dev_env/tftp_server.md
          - NFS: Embedded System/linux/embedded_linux_dev_env/nfs_server.md
          - ARM交叉编译工具: Embedded System/linux/embedded_linux_dev_env/arm_compiler.md
          - Ubuntu启动错误: Embedded System/linux/embedded_linux_dev_env/ubuntu_boot_error.md
          - 安全的使用rm: Embedded System/linux/embedded_linux_dev_env/rm.md
        
        - 编译系统:
          - CMake: 
            - CMake基础: Embedded System/linux/compiler/cmake/cmake_base.md
            - CMake编译静态和动态链接库: Embedded System/linux/compiler/cmake/cmake_static_library.md
            - CMake交叉编译: Embedded System/linux/compiler/cmake/cmake_cross_compile.md
            - VSCode与CMake搭配使用之基本配置: Embedded System/linux/compiler/cmake/vscode_cmake_base.md
            - VSCode与CMake搭配使用之交叉编译: Embedded System/linux/compiler/cmake/vscode_camke_cross_compile.md
          - 交叉编译:
            - cmake-stm32: Embedded System/linux/compiler/cross_compile/cmake_stm32.md
            - VSCode-STM32: Embedded System/linux/compiler/cross_compile/develop_stm32_using_vscode.md
            - 交叉编译的方法: Embedded System/linux/compiler/cross_compile/corss_compile.md
            - 交叉编译器默认的头文件和库文件搜索路径: Embedded System/linux/compiler/cross_compile/cross_compiler_default_search_path.md
            - CMake交叉编译: Embedded System/linux/compiler/cmake/cmake_cross_compile.md
            - VSCode与CMake搭配使用之交叉编译: Embedded System/linux/compiler/cmake/vscode_camke_cross_compile.md
          - Debug:
            - ARM-Linux GDB远程调试: Embedded System/linux/debug/arm_linux_gdb_debug.md
          - GNU make中的2种变量: Embedded System/linux/compiler/gnu_make_two_flavors_of_variables.md
          - GCC编译动态链接库: Embedded System/linux/compiler/gcc/gcc_dynamic_linking_library.md
          - GCC&Clang&LLVM的关系: Embedded System/linux/compiler/gcc_clang_llvm.md

        - Linux OS:
          - Linux补丁文件格式: Embedded System/linux/os/linux_pitch_file_format.md
          - shell中操作串口: Embedded System/linux/application/linux_serial_shell.md
          - 环境变量: Embedded System/linux/os/linux_environment_variable.md
          - Shell编程基础: Embedded System/linux/application/linux_shell_program.md
          - shell: Embedded System/linux/os/shell_cmd.md
          - subshell: Embedded System/linux/os/subshell.md

        - Uboot:
          - Uboot命令: Embedded System/linux/jz2440/uboot.md
          - Uboot移植: Embedded System/linux/jz2440/uboot2016_porting.md

        - Linux Device Driver:
          - 《Linux设备驱动开发详解》:
            - 书籍配套资源: Embedded System/linux/linux_driver/linux_device_driver_baohua/relate_resource.md
          - 最简单的驱动程序: Embedded System/linux/linux_driver/ld_hello_world.md
          - 最简单的平台总线设备驱动程序: Embedded System/linux/linux_driver/ld_bus_dev_drv.md
          - 设备树相关: Embedded System/linux/linux_driver/device_tree.md
          - Linux LCD驱动框架: Embedded System/linux/linux_driver/lcd_driver.md
          - Linux中断: Embedded System/linux/linux_driver/linux_irq.md

        - S3C2440开发:
          - device tree:
            - 支持设备树系统移植: Embedded System/linux/jz2440/device_tree/compile_uboot_kernel_with_device_tree.md
            - Led驱动: Embedded System/linux/jz2440/device_tree/led_drv.md
          
          - 烧写镜像文件: Embedded System/linux/jz2440/jz2440_download_image_files.md
          - Uboot打补丁编译: Embedded System/linux/jz2440/uboot_porting.md
          - Linux Kernel移植: Embedded System/linux/jz2440/linux_kernel_porting.md
          - JZ2440 dev tips: Embedded System/linux/jz2440/jz2440_dev_tips.md
        
        - VSCode:
          - VSCode编译调试多文件C项目: Embedded System/linux/vscode/vscode_build_c_project.md
          

    - Multimedia:
        - FFMPEG:
          - FFMPEG编译: Multimedia/ffmpeg_compile.md
          - FFMPEG命令: Multimedia/ffmpeg_command.md
          - FFMPEG API: Multimedia/ffmpeg_api.md
        - 音视频编码:
          - 码率、H264 Profile和Level: Multimedia/h264_bitrate_profile_level.md
          - AAC编码: Multimedia/aac.md
          - 彻底理解YUV格式: Multimedia/yuv.md
          - PCM: Multimedia/pcm.md
          - WAV: Multimedia/wav_foramt.md
          - OPUS: Multimedia/opus.md
          - Ogg: Multimedia/Ogg.md
        - EasyDarwin RTSP Server: Multimedia/easydarwin.md
        - Aliyun VOD: Multimedia/AliyunVOD/get_play_url.md
        - 光学知识点: Multimedia/optical.md
        - 音视频同步: Multimedia/av_synchronization.md
        - Linux Shell命令: Multimedia/linux_shell_cmd_for_multimedia.md


    - Other:
      - Computer Science:
        - 字符集: Embedded System/cs/character_set.md
        - 非对称加密: mbedded System/cs/RSA.md

      - Machine Learning:
        - 机器学习基础: ML/ml_basics.md
        - Tensorflow安装: ML/tensorflow_install.md
        - Tensorflow模型转换: ML/tensorflow_model.md
        - 嵌入式机器学习: 
          - 00：STM32图像分类: ML/how_to_run_dl_model_on_stm32.md

      - Python:
        - Django: Python/python_nginx_uwsgi_django.md
        - Python多线程: Python/python_thread.md
        - Python串口操作: Python/python_uart.md
        - Python数据类型转换: Python/data_type_conversion.md
        - matplotlib: 
          - matplotlib基础: Python/matplotlib/matplotlib_base.md
          - matplotlib子图: Python/matplotlib/matplotlib_subplot.md
        - 三角函数: Python/python_trigonometric.md
        - 录音与播放: Python/python_record_play.md  
        - Python代码片段: Python/snippet.md
        - Python字符串格式化: Python/python_string_format.md

      - Computer Vision:
        - OpenCV_Start: Computer Vision/opencv_start.md
        - cv_library: Computer Vision/cv_library.md
        - OpenCV4Android: Computer Vision/OpenCV4Android_001.md
        - caffe: Computer Vision/caffe.md

      - Nginx:
        - 配置静态网站服务器: Network/nginx/nginx_static_site_from_prebuild.md 
        - 配置HLS服务器: Network/nginx/nginx_hls_from_source.md

      - Hardware:
        - 电池工作时间的计算: Hardware/battery_work_time.md
        - USB-PD: Hardware/ubs_pd.md
        - TPS65987D: Hardware/TPS65987D.md
        - MAX17261电量计: Hardware/max17261.md

      - ESP8266: Embedded System/ESP8266.md

      - K210:
        - K210开发环境配置: Embedded System/k210/configure_k210_standlone_env.md
        - MairxPy开发环境配置: Embedded System/k210/configure_mairxpy_dev_env.md
        - MairxPy Snippet: Embedded System/k210/mairxpy_snippet.md

    - Tools:
      - MkDocs搭建个人WiKi知识管理系统: 
        - 1.MkDocs - 初识: Tools/mkdocs/mkdocs_intro.md
        - 2.MkDocs - 部署到Github Pages: Tools/mkdocs/mkdocs_deploy_githubpages.md
        - 3.MkDocs - 部署到Nginx: Tools/mkdocs/mkdocs_deploy_nginx.md
        - 4.MkDocs - Wiki样式配置: Tools/mkdocs/mkdocs_theme.md
      - 嵌入式开发神兵利器: Tools/embedded_develop_tools.md
      - VPN:
        - 配置参数: Tools/VPN/ss_parameter.md
        - Shadowsocks Ubuntu客户端: Tools/VPN/Shadowsocks_client_for_ubuntu.md
        - ShadowsocksR Ubuntu客户端: Tools/VPN/ShadowsocksR_client_for_ubuntu.md
        - SSR For Ubuntu: Tools/VPN/ssr_client_for_ubuntu.md
        - ShadowsocksR Ubuntu服务端: Tools/VPN/ShadowsocksR_server_for_ubuntu.md

      - VIM:
        - VIM基础: Tools/VIM/vim_base.md
        - 使用VIM-Plug配合NERDTree: Tools/VIM/vim_plug_nerdtree.md
        - VIM插件配置: Tools/VIM/vim_configure.md
        - VIM使用: Tools/VIM/vim_usage.md 

      - VSCode: 
        - VSCode通过SSH连接服务器实现远程编辑: Tools/vscode/ssh_remote.md

      - Markdown中的一些技巧: Tools/markdown.md
      - git command: Tools/git_command.md

      - 局域网访问Jupyter Notebook: Tools/JupyterNotebook.md
      - UML: Tools/PlantUML.md

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Frank'
    
# Configuration
theme:
  # name: 'mkdocs'
  # name: 'flatly'
  name: 'united'
  # name: 'simplex'

  # default is en
  language: 'en'

  # default is true
  highlightjs: true

  # deafult is github
  hljs_style: github
  hljs_languages:
    - c
    - c++
    - nginx
    - java
    - python
    - shell session
    - yaml
    
extra:
# Chinese is not supported  
  search:
    language: 'en'
      
# Extensions
markdown_extensions:
  - admonition
  - footnotes

  # code style
  # - codehilite:
  #     guess_lang: false
  #     linenums: false
  - toc:
      permalink: '#'

extra_css:
    - css/extra.css

plugins:
    - search
